# Generated by Django 3.2.1 on 2022-01-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Round2database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=False, max_length=20)),
                ('roll', models.CharField(blank=True, default=False, max_length=9)),
                ('number', models.IntegerField(blank=True, default=False)),
                ('email', models.EmailField(blank=True, default=False, max_length=254)),
            ],
        ),
    ]
