# Generated by Django 3.2.1 on 2022-01-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastersheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round2database',
            name='number',
            field=models.CharField(blank=True, default=False, max_length=14),
        ),
    ]
