# Generated by Django 3.2.1 on 2022-01-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastersheet', '0003_auto_20220110_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='round2database',
            name='slot',
            field=models.CharField(blank=True, default=False, max_length=15),
        ),
    ]
