# Generated by Django 3.2.1 on 2022-01-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(blank=True, default=False, max_length=10)),
                ('slot', models.CharField(blank=True, default=False, max_length=15)),
                ('datestamp', models.DateField(auto_now_add=True, null=True)),
                ('timestamp', models.TimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
