# Generated by Django 3.2.1 on 2022-01-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_alter_database_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='name',
            field=models.CharField(blank=True, default=True, max_length=50),
        ),
    ]
