# Generated by Django 3.2.1 on 2022-01-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_database_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='file',
            field=models.FileField(blank=True, default=False, upload_to=''),
        ),
    ]
