# Generated by Django 3.2.1 on 2022-01-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0004_database_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
