# Generated by Django 3.2.1 on 2022-01-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0005_alter_database_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='interviewer',
            field=models.CharField(blank=True, default=False, max_length=30),
        ),
    ]
