# Generated by Django 3.2.1 on 2022-01-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0006_database_interviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='interviewer',
        ),
    ]
